<pre>
<center><b><h1>Kanasagara Het S.</b></center>     
<pre>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("preprocessed_housing_ordered.csv")
df.sample(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
6456,0.758531,-0.712515,1.538349,-0.561874,-0.555196,-0.660945,-0.589923,-0.321654,0.568009,0,1,0,0,0
6467,0.758531,-0.717197,0.108104,-0.225876,-0.261907,-0.281232,-0.218507,0.190248,0.392955,0,1,0,0,0
12898,-0.883609,1.408370,-0.924851,0.057407,-0.085456,-0.262688,-0.045877,-0.060255,-0.581976,0,1,0,0,0
13254,0.953192,-0.707833,-1.004309,0.557966,0.009922,0.265378,-0.006643,1.183734,0.383422,0,1,0,0,0
10835,0.823418,-0.913835,-0.289187,-0.283633,-0.197526,-0.354525,-0.187120,0.317158,0.335759,1,0,0,0,0

In [3]:
df.shape

(20640, 14)

In [4]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', '<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY',
       'NEAR OCEAN'],
      dtype='object')

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

In [6]:
X = df.drop(columns = "median_house_value")
y = df["median_house_value"]

In [7]:
X

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
0,-1.327835,1.052548,0.982143,-0.804819,-0.972476,-0.974429,-0.977033,2.344766,0,0,0,1,0
1,-1.322844,1.043185,-0.607019,2.045890,1.357143,0.861439,1.669961,2.332238,0,0,0,1,0
2,-1.332827,1.038503,1.856182,-0.535746,-0.827024,-0.820777,-0.843637,1.782699,0,0,0,1,0
3,-1.337818,1.038503,1.856182,-0.624215,-0.719723,-0.766028,-0.733781,0.932968,0,0,0,1,0
4,-1.337818,1.038503,1.856182,-0.462404,-0.612423,-0.759847,-0.629157,-0.012881,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-0.758826,1.801647,-0.289187,-0.444985,-0.388283,-0.512592,-0.443449,-1.216128,0,1,0,0,0
20636,-0.818722,1.806329,-0.845393,-0.888704,-0.922403,-0.944405,-1.008420,-0.691593,0,1,0,0,0
20637,-0.823713,1.778237,-0.924851,-0.174995,-0.123608,-0.369537,-0.174042,-1.142593,0,1,0,0,0
20638,-0.873626,1.778237,-0.845393,-0.355600,-0.304827,-0.604429,-0.393753,-1.054583,0,1,0,0,0
20639,-0.833696,1.750146,-1.004309,0.068408,0.188757,-0.033977,0.079672,-0.780129,0,1,0,0,0

In [8]:
y

0        2.129631
1        1.314156
2        1.258693
3        1.165100
4        1.172900
           ...
20635   -1.115804
20636   -1.124470
20637   -0.992746
20638   -1.058608
20639   -1.017878
Name: median_house_value, Length: 20640, dtype: float64

In [9]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.3 , random_state = 42)

In [10]:
X_train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
7061,0.773505,-0.796789,0.505394,-0.108071,-0.331056,-0.183213,-0.239432,0.137137,1,0,0,0,0
14689,1.237697,-1.330521,-0.686477,-0.207541,-0.006769,-0.376602,-0.009258,-0.530363,0,0,0,0,1
17323,-0.284652,-0.487786,-0.368645,-0.474322,-0.607654,-0.613260,-0.561151,0.174720,0,0,0,0,1
10056,-0.713904,1.698646,-1.163225,-0.836906,-0.920018,-0.992090,-0.945646,-0.400716,0,1,0,0,0
15750,-1.437644,1.001048,1.856182,0.253138,0.408127,0.088767,0.430163,-0.296809,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,0.803453,-0.867017,0.505394,-0.598545,-0.800795,-0.677723,-0.739013,1.315592,1,0,0,0,0
11964,1.067992,-0.754652,0.346478,0.205466,0.079072,0.289220,-0.132192,-0.431983,0,1,0,0,0
5390,0.593818,-0.749970,0.584852,-0.245128,0.076687,0.291870,0.071825,-0.492832,1,0,0,0,0
860,-1.193070,0.912092,-1.083767,0.430534,0.143452,0.310414,0.155525,0.973025,1,0,0,0,0
15795,-1.422670,1.001048,1.856182,0.728944,1.855496,1.053944,1.941984,-0.681749,0,0,0,1,0

In [11]:
y_train

7061    -0.113142
14689   -0.321994
17323    0.458817
10056   -0.613173
15750    2.540411
           ...
11284    0.193636
11964   -0.945083
5390     0.132107
860      0.664202
15795    1.023843
Name: median_house_value, Length: 14448, dtype: float64

In [12]:
from sklearn.metrics import r2_score
import numpy as np

model = LinearRegression()

model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

print("Train R2 Score:", r2_score(y_train, y_train_pred))
print("Test R2 Score :", r2_score(y_test, y_test_pred))

Train R2 Score: 0.6470480227253683
Test R2 Score : 0.6393611711434395

In [13]:
print(model.coef_)

[-0.46013883 -0.46118261  0.12062252 -0.11101941  0.3842319  -0.36631703
  0.1401925   0.64651846 -0.15931572 -0.51528292  1.01830127 -0.21188439
 -0.13181823]

# Multiple Linear Regression Algorithm With Gradient Descent Implementation

In [ ]:
import numpy as np

m, n = X.shape

weights = np.zeros(n)
bias = 0

learning_rate = 0.01
epochs = 50000

loss_history = []

for epoch in range(epochs):

    y_pred = np.dot(X, weights) + bias

    error = y_pred - y

    loss = np.mean(error ** 2)
    loss_history.append(loss)

    dw = (2 / m) * np.dot(X.T, error)
    db = (2 / m) * np.sum(error)

    weights -= learning_rate * dw
    bias -= learning_rate * db

    if epoch % 1000 == 0:
        print(f"Epoch {epoch} Loss = {loss:.4f}")

Epoch 0 Loss = 1.0000
Epoch 1000 Loss = 0.3576
Epoch 2000 Loss = 0.3559
Epoch 3000 Loss = 0.3553
Epoch 4000 Loss = 0.3552
Epoch 5000 Loss = 0.3551
Epoch 6000 Loss = 0.3550
Epoch 7000 Loss = 0.3550

In [20]:
print("\nWeights:")
print(weights)

Weights:
[-0.45832463 -0.46584937  0.11567614 -0.08906708  0.25983986 -0.38595343
  0.25718313  0.63790779  0.07440592 -0.27024686  0.06917042  0.04345774
  0.11619076]

In [21]:
print(model.coef_)

[-0.46013883 -0.46118261  0.12062252 -0.11101941  0.3842319  -0.36631703
  0.1401925   0.64651846 -0.15931572 -0.51528292  1.01830127 -0.21188439
 -0.13181823]

In [ ]:
# Weights:
# [-0.45832463 -0.46584937  0.11567614 -0.08906708  0.25983986 -0.38595343
#   0.25718313  0.63790779  0.07440592 -0.27024686  0.06917042  0.04345774
#   0.11619076]